server:
  # 8004 表示注册到 zookeeper 服务器的支付服务提供者端口号
  port: 8004

spring:
  application:
    # 服务别名---注册zookeeper到注册中心的名称
    name: cloud-provider-zk-payment

  cloud:
    zookeeper:
      # 默认 localhost:2181
      connect-string: localhost:2181
