server:
  port: 7001

spring:
  application:
    name: cloud-eureka-service

eureka:
  instance:
    # eureka 服务端的实例名称
    # 单机
    hostname: localhost
    # hostname: eureka7001.com
    # Eureka 客户端向服务端发送心跳的时间间隔,单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
    # Eureka 服务端在收到最后一次心跳后等待时间上限 ,单位为秒(默认是90秒),超时剔除服务
    lease-expiration-duration-in-seconds: 2
  server:
    # 禁用自我保护,保证不可用服务被及时删除
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 2000
  client:
    # false 表示不向注册中心注册自己
    # 表示是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    register-with-eureka: false
    # false 表示自己端就是注册中心,我的职责就是维护服务实例,并不需要检索服务
    # 表示表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    fetch-registry: false
    service-url:
      # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      # 单机
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 相互注册
      # defaultZone: http://eureka7002.com:7002/eureka/
